# Generated by Django 3.2 on 2024-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('vote_avg', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('released_date', models.DateField()),
                ('now_playing', models.BooleanField()),
                ('coming_soon', models.BooleanField()),
                ('belongs_to_collection', models.JSONField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
