databases:
  - name: shih-tzu
    plan: free
    databaseName: shihtzu
    user: shihtzu_user

services:
  - type: web
    plan: free
    name: shih-tzu
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Shih_Tzu.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4