# Generated by Django 4.2.8 on 2024-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_popularity'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_movies',
            field=models.ManyToManyField(related_name='liked_users', to='movies.movie'),
        ),
    ]
